<a href="https://colab.research.google.com/github/sakshitiwari1234/Deep_Learning/blob/main/Gradient_Descent_Part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline




In [3]:
df = pd.read_csv("/content/insurance_dataset - Sheet1.csv")
df.head()

age  affordibility  insurance
0   22              1          0
1   25              0          0
2   47              1          1
3   52              0          0
4   46              1          1

In [7]:
from sklearn.model_selection import train_test_split
xtrain , xtest , ytrain , ytest = train_test_split(df[['age','affordibility']],df.insurance, test_size = 0.2 , random_state=2)

In [8]:
len(xtrain)

21

In [9]:
len(ytrain)

21

In [10]:
len(xtest)

6

In [22]:

# scaling the dataset by dividing it by 100.
xtrain_scaled = xtrain.copy()
xtrain_scaled['age']= xtrain_scaled['age']/100


xtest_scaled = xtest.copy()
xtest_scaled['age'] = xtest_scaled['age']  /100

In [12]:
xtrain_scaled

age  affordibility
6   0.55              0
3   0.52              0
17  0.58              1
24  0.50              1
14  0.49              1
4   0.46              1
10  0.18              1
5   0.56              1
19  0.18              1
1   0.25              0
2   0.47              1
7   0.60              0
23  0.45              1
21  0.26              0
18  0.19              0
11  0.28              1
22  0.40              1
26  0.23              1
13  0.29              0
15  0.55              1
8   0.62              1

In [14]:
# building neural network for predicting the insurance.

model = keras.Sequential({
    keras.layers.Dense(1,input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')

})

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [24]:
#model compile

model.compile(optimizer = 'adam', loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(xtrain_scaled, ytrain ,epochs = 1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.7143 - loss: 0.5667
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.7143 - loss: 0.5666
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.7143 - loss: 0.5665
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7143 - loss: 0.5664
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7143 - loss: 0.5662
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.7143 - loss: 0.5661
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.7143 - loss: 0.5660
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7143 - loss: 0.5659
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7143 - loss: 0.5658
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7143 - loss: 0.5657
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7143 - loss: 0.5656
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy:

In [25]:
model.evaluate(xtest_scaled , ytest)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 0.5000 - loss: 0.6567


[0.6567086577415466, 0.5]

In [26]:
xtest_scaled

age  affordibility
25  0.54              1
0   0.22              1
9   0.61              1
20  0.21              1
16  0.25              0
12  0.27              0

In [27]:
model.predict(xtest_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step


array([[0.77049977],
       [0.6121261 ],
       [0.7983905 ],
       [0.60651064],
       [0.30023432],
       [0.31023893]], dtype=float32)

In [28]:
ytest

25    1
0     0
9     1
20    0
16    1
12    0
Name: insurance, dtype: int64

In [29]:

# knowing the weights
coef , intercept = model.get_weights()

In [30]:
coef,intercept

(array([[2.358991 ],
        [1.3732102]], dtype=float32),
 array([-1.43593], dtype=float32))

In [32]:
# Building neural network from scratch without tensorflow.


In [34]:
def sigmoid(x):
  import math
  return 1 / (1 + math.exp(-x))
sigmoid(12)


0.9999938558253978

In [35]:
def prediction_function(age, affordibility):
 weighted_sum= coef[0] * age + coef[1]*affordibility + intercept
 return sigmoid(weighted_sum)



In [38]:
prediction_function(54,1)

/tmp/ipython-input-34-3787363639.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


1.0

In [51]:
# implementing gradient descent method in python from scratch
def logloss(y_true , y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i,epsilon) for i in y_predicted]
  y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true* np.log(y_predicted_new)+ (1-y_true)* np.log(1-y_predic))


In [52]:
def sigmoid_numpy(x):
  import math
  return 1 / (1 + np.exp(-x))

sigmoid_numpy(np.array([12,0,1]))


array([0.99999386, 0.5       , 0.73105858])

In [53]:
def gradient_descent(age ,affordability , y_true , epochs , loss_threshold):
  w1=w2 = 1
  bias = 0
  rate = 0.5
  n =len(age)

  for i in range(epochs):
    weighted_sum = w1 * age + w2 * affordability + bias
    y_predicted = sigmoid_numpy(weighted_sum)

    loss = log_loss(y_true, y_predicted)

    w1d = (1/n)* np.dot(np.transpose(age), (y_predicted - y_true))
    w2d = (1/n)* np.dot(np.transpose(affordability), (y_predicted - y_true))

    bias_d = np.mean(y_predicted = y_true)

    w1=w1-rate*w1d
    w2 = w2-rate*w2d
    bias = bias - rate * bias_d

    print(f'Epoch:{i}, w1:{w1}, w2:{w2} , bias:{bias}, loss:{loss}')

    if loss <= loss_threshold:
      break

  return w1,w2,bias






In [54]:
gradient_descent(xtrain_scaled['age'], xtrain_scaled['affordibility'], ytrain ,100 , 0.4631)

NameError: name 'log_loss' is not defined