<a href="https://colab.research.google.com/github/sakshitiwari1234/Deep_Learning/blob/main/Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
# df = pd.read_csv("/content/important-data.xlsx")

In [11]:
data = {'age' : [22,25,47],
'afford' : [1,0,1],
'bought' : [0,0,1]}

In [14]:
df = pd.DataFrame(data)

In [15]:
df

age  afford  bought
0   22       1       0
1   25       0       0
2   47       1       1

In [16]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(df[['age', 'afford']], df.bought,test_size = 0.2, random_state = 25)

In [17]:
len(xtrain)

2

In [18]:
df.shape

(3, 3)

In [19]:
len(xtest)

1

In [22]:
x_train_scaled = xtrain.copy()
x_train_scaled['age'] = x_train_scaled['age'] / 100


In [25]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape = (2,), activation = 'sigmoid', kernel_initializer="ones", bias_initializer='zeros')
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [27]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

model.fit(x_train_scaled, ytrain , epochs =3)

Epoch 1/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 938ms/step - accuracy: 0.5000 - loss: 0.8428
Epoch 2/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5000 - loss: 0.8422
Epoch 3/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.8416


In [28]:
model.evaluate(x_test, ytest)

NameError: name 'x_test' is not defined

In [29]:
xtest

age  afford
1   25       0

In [30]:
ytest

1    0
Name: bought, dtype: int64

In [31]:
coef , intercept = model.get_weights()
coef , intercept

(array([[0.99700046],
        [0.99700016]], dtype=float32),
 array([-0.00299983], dtype=float32))

In [32]:
def sigmoid(x):
  import math
  return 1/(1+ math.exp(-x))

In [33]:
sigmoid(23)

0.9999999998973812

In [38]:
def prediction_function(age , afford):
  wight =  coef[0] * age + coef[1] * afford + intercept
  return sigmoid[wight]

In [42]:
# prediction_function(23,2

In [43]:
def log_loss(y_true , y_predicted):
  epsilon = le=15
  y_predicted_new = [max(i, epsilon) for i in y_predicted]
  y_predicted_new = [min(i, 1-epsilon) for i in y_predicted]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true* np.log(y_predicted_new)+ (1-y_true)* np.log(1-y_predicted_new))


In [44]:
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [46]:
def gradient_des(age, afford, y_true, epochs):
  w1 = w2 = 1
  bias = 0
  rate = 0.5
  n = len(age)

  for i in range(epochs):
    w1 = age + w2 + afford + bias

In [48]:
gradient_des(x_train_scaled['age'], x_train_scaled['afford'], ytrain, 2)

In [50]:
gradient_des

<function __main__.gradient_des(age, afford, y_true, epochs)>